### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by XXXXXuan** [rwanwork/sam2irs#3]
Excuse me. Sorry that I'm confused while I'm using this. 

I would like to find a sensible criteria to judge my RNA-Seq data about Intron reteintion events and I found your amazing method. Actually my coding level is poor, so I need to find a script or software to solve this question. 

But, when I used this with following code, it didn't work: 
cat Col_rep1.sam | ../Perl/sam2irs.pl --chrlist arabidopsis.sizes --gtf ~/ref_seqs/Arabidopsis_thaliana.TAIR10.49.gtf 1>Col_rep1.output.gtf 2>error.txt

And I found that inside the "error.txt", there was: -bash: ../Perl/sam2irs.pl: Permission denied
So,  I don't know what happened. (I just put the Perl folder into the server, is that OK? Do I need to install it any way? 

Thank you most sincerely.

**Comment by rwanwork** [comment]
Hi,

Thank you for your interest in our work!  How did you download `sam2irs.pl`?  Did you download it from your web browser?  Or did you "clone" it using `git clone`?  Of the two options, you should definitely clone it.  See [this](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository) for an explanation.

If you had cloned it, I don't think you should have seen this problem.  If you did clone it, then it might mean that I made a mistake and I can look into it.

You need "execute" permissions on the script.  See [here](https://bash.cyberciti.biz/guide/Setting_up_permissions_on_a_script).  You can do that by typing `chmod u+x ../Perl/sam2irs.pl`.

No, you don't need to install it, but you should use "clone" as I think it would turn on execute permissions for you automatically.

On that note, the main README.md has a running example [here](https://github.com/rwanwork/sam2irs/#running-example).  Before you dive into your own program, you should make sure you can get the example working.  As the example is much smaller than your own input, it would be easier to troubleshoot.

**Comment by XXXXXuan** [comment]
Thank you very much! I'll try to use `git clone` :) If I have any question after doing that, I'll let you know.

**Comment by XXXXXuan** [comment]
Hi, 
I'm sorry to bother you again. It still have the following error...

Can't locate AppConfig.pm in @INC (you may need to install the AppConfig module) (@INC contains: /users/chenxy/biotools/sam2irs/Perl /users/chenxy/miniconda3/envs/py2/lib/perl5/5.32/site_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/site_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/5.32/vendor_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/vendor_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/5.32/core_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/core_perl .) at ../Perl/sam2irs.pl line 27.
BEGIN failed--compilation aborted at ../Perl/sam2irs.pl line 27 (#1)
    (F) You said to do (or require, or use) a file that couldn't be found.
    Perl looks for the file in all the locations mentioned in @INC, unless
    the file name included the full path to the file.  Perhaps you need
    to set the PERL5LIB or PERL5OPT environment variable to say where the
    extra library is, or maybe the script needs to add the library name
    to @INC.  Or maybe you just misspelled the name of the file.  See
    "require" in perlfunc and lib.
    
Uncaught exception from user code:
	Can't locate AppConfig.pm in @INC (you may need to install the AppConfig module) (@INC contains: /users/chenxy/biotools/sam2irs/Perl /users/chenxy/miniconda3/envs/py2/lib/perl5/5.32/site_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/site_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/5.32/vendor_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/vendor_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/5.32/core_perl /users/chenxy/miniconda3/envs/py2/lib/perl5/core_perl .) at ../Perl/sam2irs.pl line 27.
	BEGIN failed--compilation aborted at ../Perl/sam2irs.pl line 27.

**Comment by rwanwork** [comment]
Hi,

So, as the instructions said, you need to install AppConfig.  Have you done that?  It seems you have not?

But, it does seem like you're using conda.  Did you install the environment by typing `conda env create -f environment.yml`?  I suppose I should have put that explicitly in the instructions.  Maybe I will add that now...

**Comment by XXXXXuan** [comment]
Hi, 

I've already installed the conda package, perl-appconfig and the environment by typing `conda env create -f environment.yml`, and I've already finished the example file which you gave. Thank you VERY VERY much! 

By the way, happy Thanksgiving Day and MERRY CHRISTMAS!!! Hope more and more people can use your amazing work :) 

Best wishes, 
Xuanyi

**Comment by XXXXXuan** [comment]
Hi, 
There is a new problem when I'm using my gtf file to calculate irs...

EE	Could not match gene name in "gene_id ""AT1G01010""; transcript_id ""AT1G01010.1""; exon_number ""1""; gene_name ""NAC001""; gene_source ""araport11""; gene_biotype ""protein_coding""; transcript_source ""araport11""; transcript_biotype ""protein_coding""; exon_id ""AT1G01010.1.exon1"";"
.
And the first 5 lines of the gtf file is(Downloaded from ensemble plants, 9 colomns, the header information was already deleted): 

1       araport11       gene    3631    5899    .       +       .       "gene_id ""AT1G01010""; gene_name ""NAC001""; gene_source ""araport11""; gene_biotype ""protein_coding"";"
1       araport11       transcript      3631    5899    .       +       .       "gene_id ""AT1G01010""; transcript_id ""AT1G01010.1""; gene_name ""NAC001""; gene_source ""araport11""; gene_biotype ""protein_coding""; transcript_source ""araport11""; transcript_biotype ""protein_coding"";"
1       araport11       exon    3631    3913    .       +       .       "gene_id ""AT1G01010""; transcript_id ""AT1G01010.1""; exon_number ""1""; gene_name ""NAC001""; gene_source ""araport11""; gene_biotype ""protein_coding""; transcript_source ""araport11""; transcript_biotype ""protein_coding""; exon_id ""AT1G01010.1.exon1"";"
1       araport11       CDS     3760    3913    .       +       0       "gene_id ""AT1G01010""; transcript_id ""AT1G01010.1""; exon_number ""1""; gene_name ""NAC001""; gene_source ""araport11""; gene_biotype ""protein_coding""; transcript_source ""araport11""; transcript_biotype ""protein_coding""; protein_id ""AT1G01010.1"";"
1       araport11       start_codon     3760    3762    .       +       0       "gene_id ""AT1G01010""; transcript_id ""AT1G01010.1""; exon_number ""1""; gene_name ""NAC001""; gene_source ""araport11""; gene_biotype ""protein_coding""; transcript_source ""araport11""; transcript_biotype ""protein_coding"";"

Hoping to get your help!

**Comment by XXXXXuan** [comment]
I've already finished the work by changing the original gtf file! Thank you so much, again!

**Comment by rwanwork** [comment]
Sorry for the late reply!  I had a busy weekend and wasn't able to reply to you!

Whatever GTF file you used to do alignment, you should use the same one with the `sam2irs.pl` script.  If you feel that the error message of `sam2irs.pl` is a bit unfriendly, I can look into improving it.

Thanks again for using our software and sorry again, for the late reply!

**Comment by XXXXXuan** [comment]
Never mind. weekend is just weekend! 
For me, it would be better if you can improve it. It seems that the `sam2irs.pl` script cannot recognize the gtf file downloaded from ensembl plants. Actually I don't know other speices, such as animals. And I can give you the link if you wanna improve this :)

link: https://drive.google.com/file/d/1RQEpxlhhR9tBrhblftQBtPzwdv1E4H3_/view?usp=sharing

**Comment by rwanwork** [comment]
The program doesn't recognize a gtf file based on species.  And I have no intention of doing that.

It recognizes gtf files based on the definition for gtf files.  Of course, if there is something special between mammals and plants that I missed, I will certainly take that into consideration.

Thank you for the feedback!  I really appreciate it!
